import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative w-screen h-screen bg-slate-100 text-[#0C1421] antialiased [&::-webkit-scrollbar]:hidden flex flex-col justify-center items-center lg:px-6 py-4 lg:py-20 max-w-screen-xl mx-auto`}>
          {children}
      </body>
    </html>
  );
}
